In [2]:
import pandas as pd

# Dataset inladen
df = pd.read_csv('../data/ufc-master.csv')

# Hoeveel rijen en kolommen?
print("Vorm van de dataset:", df.shape)

# Eerste 5 rijen bekijken
df.head()

Vorm van de dataset: (6528, 118)

,RedFighter,BlueFighter,RedOdds,BlueOdds,RedExpectedValue,BlueExpectedValue,Date,Location,Country,Winner,...,FinishDetails,FinishRound,FinishRoundTime,TotalFightTimeSecs,RedDecOdds,BlueDecOdds,RSubOdds,BSubOdds,RKOOdds,BKOOdds
0,Alexandre Pantoja,Kai Asakura,-250.0,215.0,40.0000,215.0,2024-12-07,"Las Vegas, Nevada, USA",USA,Red,...,Rear Naked Choke,2.0,2:05,425.0,300.0,800.0,150.0,2500.0,400.0,350.0
1,Shavkat Rakhmonov,Ian Machado Garry,-210.0,295.0,47.6190,295.0,2024-12-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,5.0,5:00,1500.0,250.0,650.0,180.0,3000.0,240.0,700.0
2,Ciryl Gane,Alexander Volkov,-380.0,300.0,26.3158,300.0,2024-12-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,3.0,5:00,900.0,-160.0,450.0,1100.0,3000.0,350.0,1100.0
3,Bryce Mitchell,Kron Gracie,-950.0,625.0,10.5263,625.0,2024-12-07,"Las Vegas, Nevada, USA",USA,Red,...,Elbows,3.0,0:39,639.0,-200.0,1100.0,380.0,1400.0,500.0,4000.0
4,Nate Landwehr,Dooho Choi,-130.0,110.0,76.9231,110.0,2024-12-07,"Las Vegas, Nevada, USA",USA,Blue,...,Elbows,3.0,3:21,801.0,275.0,550.0,500.0,700.0,300.0,250.0

In [10]:
print(df.columns.tolist())

['RedFighter', 'BlueFighter', 'RedOdds', 'BlueOdds', 'RedExpectedValue', 'BlueExpectedValue', 'Date', 'Location', 'Country', 'Winner', 'TitleBout', 'WeightClass', 'Gender', 'NumberOfRounds', 'BlueCurrentLoseStreak', 'BlueCurrentWinStreak', 'BlueDraws', 'BlueAvgSigStrLanded', 'BlueAvgSigStrPct', 'BlueAvgSubAtt', 'BlueAvgTDLanded', 'BlueAvgTDPct', 'BlueLongestWinStreak', 'BlueLosses', 'BlueTotalRoundsFought', 'BlueTotalTitleBouts', 'BlueWinsByDecisionMajority', 'BlueWinsByDecisionSplit', 'BlueWinsByDecisionUnanimous', 'BlueWinsByKO', 'BlueWinsBySubmission', 'BlueWinsByTKODoctorStoppage', 'BlueWins', 'BlueStance', 'BlueHeightCms', 'BlueReachCms', 'BlueWeightLbs', 'RedCurrentLoseStreak', 'RedCurrentWinStreak', 'RedDraws', 'RedAvgSigStrLanded', 'RedAvgSigStrPct', 'RedAvgSubAtt', 'RedAvgTDLanded', 'RedAvgTDPct', 'RedLongestWinStreak', 'RedLosses', 'RedTotalRoundsFought', 'RedTotalTitleBouts', 'RedWinsByDecisionMajority', 'RedWinsByDecisionSplit', 'RedWinsByDecisionUnanimous', 'RedWinsByKO', 'RedWinsBySubmission', 'RedWinsByTKODoctorStoppage', 'RedWins', 'RedStance', 'RedHeightCms', 'RedReachCms', 'RedWeightLbs', 'RedAge', 'BlueAge', 'LoseStreakDif', 'WinStreakDif', 'LongestWinStreakDif', 'WinDif', 'LossDif', 'TotalRoundDif', 'TotalTitleBoutDif', 'KODif', 'SubDif', 'HeightDif', 'ReachDif', 'AgeDif', 'SigStrDif', 'AvgSubAttDif', 'AvgTDDif', 'EmptyArena', 'BMatchWCRank', 'RMatchWCRank', 'RWFlyweightRank', 'RWFeatherweightRank', 'RWStrawweightRank', 'RWBantamweightRank', 'RHeavyweightRank', 'RLightHeavyweightRank', 'RMiddleweightRank', 'RWelterweightRank', 'RLightweightRank', 'RFeatherweightRank', 'RBantamweightRank', 'RFlyweightRank', 'RPFPRank', 'BWFlyweightRank', 'BWFeatherweightRank', 'BWStrawweightRank', 'BWBantamweightRank', 'BHeavyweightRank', 'BLightHeavyweightRank', 'BMiddleweightRank', 'BWelterweightRank', 'BLightweightRank', 'BFeatherweightRank', 'BBantamweightRank', 'BFlyweightRank', 'BPFPRank', 'BetterRank', 'Finish', 'FinishDetails', 'FinishRound', 'FinishRoundTime', 'TotalFightTimeSecs', 'RedDecOdds', 'BlueDecOdds', 'RSubOdds', 'BSubOdds', 'RKOOdds', 'BKOOdds']

In [3]:
# Hoeveel ontbrekende waarden per kolom?
ontbrekend = df.isnull().sum()
ontbrekend[ontbrekend > 0].sort_values(ascending=False)

BWFeatherweightRank      6527
RWFeatherweightRank      6519
BPFPRank                 6461
BWFlyweightRank          6455
RWFlyweightRank          6432
BWStrawweightRank        6428
BWBantamweightRank       6421
BWelterweightRank        6409
BBantamweightRank        6409
BLightweightRank         6408
BLightHeavyweightRank    6408
BFeatherweightRank       6404
BFlyweightRank           6398
BMiddleweightRank        6391
RWStrawweightRank        6382
BHeavyweightRank         6380
RWBantamweightRank       6374
RFeatherweightRank       6351
RBantamweightRank        6347
RMiddleweightRank        6346
RLightweightRank         6344
RLightHeavyweightRank    6344
RHeavyweightRank         6342
RFlyweightRank           6340
RWelterweightRank        6337
RPFPRank                 6275
BMatchWCRank             5328
RMatchWCRank             4749
FinishDetails            3636
EmptyArena               1486
BKOOdds                  1360
BSubOdds                 1359
RSubOdds                 1336
RKOOdds                  1334
BlueDecOdds              1116
RedDecOdds               1087
BlueAvgSigStrLanded       930
BlueAvgTDPct              842
BlueAvgTDLanded           833
BlueAvgSubAtt             832
BlueAvgSigStrPct          765
FinishRound               622
FinishRoundTime           622
TotalFightTimeSecs        622
RedAvgSigStrLanded        455
RedAvgTDPct               367
RedAvgSigStrPct           357
RedAvgSubAtt              357
RedAvgTDLanded            357
Finish                    238
RedExpectedValue          227
RedOdds                   227
BlueOdds                  226
BlueExpectedValue         226
BlueStance                  3
dtype: int64

In [16]:
# Volledige lijst met percentages
ontbrekend = df.isnull().sum()
ontbrekend_pct = (ontbrekend / len(df) * 100).round(1)

result = pd.DataFrame({
    'Ontbrekend': ontbrekend,
    'Percentage': ontbrekend_pct
})

result[result['Ontbrekend'] > 0].sort_values('Percentage', ascending=False)

                       Ontbrekend  Percentage
BWFeatherweightRank          6527       100.0
RWFeatherweightRank          6519        99.9
BPFPRank                     6461        99.0
BWFlyweightRank              6455        98.9
BWStrawweightRank            6428        98.5
RWFlyweightRank              6432        98.5
BWBantamweightRank           6421        98.4
BWelterweightRank            6409        98.2
BLightHeavyweightRank        6408        98.2
BLightweightRank             6408        98.2
BBantamweightRank            6409        98.2
BFeatherweightRank           6404        98.1
BFlyweightRank               6398        98.0
BMiddleweightRank            6391        97.9
RWStrawweightRank            6382        97.8
BHeavyweightRank             6380        97.7
RWBantamweightRank           6374        97.6
RFeatherweightRank           6351        97.3
RLightweightRank             6344        97.2
RBantamweightRank            6347        97.2
RHeavyweightRank             6342        97.2
RLightHeavyweightRank        6344        97.2
RMiddleweightRank            6346        97.2
RWelterweightRank            6337        97.1
RFlyweightRank               6340        97.1
RPFPRank                     6275        96.1
BMatchWCRank                 5328        81.6
RMatchWCRank                 4749        72.7
FinishDetails                3636        55.7
EmptyArena                   1486        22.8
BSubOdds                     1359        20.8
BKOOdds                      1360        20.8
RSubOdds                     1336        20.5
RKOOdds                      1334        20.4
BlueDecOdds                  1116        17.1
RedDecOdds                   1087        16.7
BlueAvgSigStrLanded           930        14.2
BlueAvgTDPct                  842        12.9
BlueAvgTDLanded               833        12.8
BlueAvgSubAtt                 832        12.7
BlueAvgSigStrPct              765        11.7
FinishRound                   622         9.5
FinishRoundTime               622         9.5
TotalFightTimeSecs            622         9.5
RedAvgSigStrLanded            455         7.0
RedAvgTDPct                   367         5.6
RedAvgSigStrPct               357         5.5
RedAvgSubAtt                  357         5.5
RedAvgTDLanded                357         5.5
Finish                        238         3.6
RedExpectedValue              227         3.5
BlueOdds                      226         3.5
BlueExpectedValue             226         3.5
RedOdds                       227         3.5
BlueStance                      3         0.0

In [5]:
# Volledige lijst printen zonder afkapping
pd.set_option('display.max_rows', None)
result[result['Ontbrekend'] > 0].sort_values('Percentage', ascending=False)

NameError: name 'result' is not defined

In [6]:
kolommen_verwijderen = [
    # Ranking kolommen (bijna alles leeg)
    'BWFeatherweightRank', 'RWFeatherweightRank', 'BPFPRank', 'BWFlyweightRank',
    'RWFlyweightRank', 'BWStrawweightRank', 'BWBantamweightRank', 'BWelterweightRank',
    'BLightHeavyweightRank', 'BLightweightRank', 'BBantamweightRank', 'BFeatherweightRank',
    'BFlyweightRank', 'BMiddleweightRank', 'RWStrawweightRank', 'BHeavyweightRank',
    'RWBantamweightRank', 'RFeatherweightRank', 'RLightweightRank', 'RBantamweightRank',
    'RHeavyweightRank', 'RLightHeavyweightRank', 'RMiddleweightRank', 'RWelterweightRank',
    'RFlyweightRank', 'RPFPRank', 'BMatchWCRank', 'RMatchWCRank',
    # Post-fight info
    'Finish', 'FinishDetails', 'FinishRound', 'FinishRoundTime', 'TotalFightTimeSecs',
    # Niet relevant
    'EmptyArena', 'Location', 'Country', 'Date', 'RedFighter', 'BlueFighter',
    # Specifieke odds met veel missende waarden
    'BSubOdds', 'BKOOdds', 'RSubOdds', 'RKOOdds', 'BlueDecOdds', 'RedDecOdds',
    'RedExpectedValue', 'BlueExpectedValue'
]

df_clean = df.drop(columns=kolommen_verwijderen)
print("Kolommen over:", df_clean.shape[1])
print(df_clean.columns.tolist())

Kolommen over: 71
['RedOdds', 'BlueOdds', 'Winner', 'TitleBout', 'WeightClass', 'Gender', 'NumberOfRounds', 'BlueCurrentLoseStreak', 'BlueCurrentWinStreak', 'BlueDraws', 'BlueAvgSigStrLanded', 'BlueAvgSigStrPct', 'BlueAvgSubAtt', 'BlueAvgTDLanded', 'BlueAvgTDPct', 'BlueLongestWinStreak', 'BlueLosses', 'BlueTotalRoundsFought', 'BlueTotalTitleBouts', 'BlueWinsByDecisionMajority', 'BlueWinsByDecisionSplit', 'BlueWinsByDecisionUnanimous', 'BlueWinsByKO', 'BlueWinsBySubmission', 'BlueWinsByTKODoctorStoppage', 'BlueWins', 'BlueStance', 'BlueHeightCms', 'BlueReachCms', 'BlueWeightLbs', 'RedCurrentLoseStreak', 'RedCurrentWinStreak', 'RedDraws', 'RedAvgSigStrLanded', 'RedAvgSigStrPct', 'RedAvgSubAtt', 'RedAvgTDLanded', 'RedAvgTDPct', 'RedLongestWinStreak', 'RedLosses', 'RedTotalRoundsFought', 'RedTotalTitleBouts', 'RedWinsByDecisionMajority', 'RedWinsByDecisionSplit', 'RedWinsByDecisionUnanimous', 'RedWinsByKO', 'RedWinsBySubmission', 'RedWinsByTKODoctorStoppage', 'RedWins', 'RedStance', 'RedHeightCms', 'RedReachCms', 'RedWeightLbs', 'RedAge', 'BlueAge', 'LoseStreakDif', 'WinStreakDif', 'LongestWinStreakDif', 'WinDif', 'LossDif', 'TotalRoundDif', 'TotalTitleBoutDif', 'KODif', 'SubDif', 'HeightDif', 'ReachDif', 'AgeDif', 'SigStrDif', 'AvgSubAttDif', 'AvgTDDif', 'BetterRank']

In [7]:
# Hoeveel ontbrekende waarden zijn er nog?
print("Rijen voor opschonen:", df_clean.shape[0])

# Verwijder rijen met ontbrekende waarden
df_clean = df_clean.dropna()

print("Rijen na opschonen:", df_clean.shape[0])
print("Verwijderd:", 6528 - df_clean.shape[0], "rijen")

Rijen voor opschonen: 6528
Rijen na opschonen: 5246
Verwijderd: 1282 rijen

In [9]:
# Opgeschoonde dataset opslaan
df_clean.to_csv('../data/ufc_clean.csv', index=False)
print("Opgeslagen als ufc_clean.csv")

Opgeslagen als ufc_clean.csv